language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ar/hFL7w8ZhcHegfjePRxKa98EsrUy69Ht/8Ad3T53ggIJP+AoyzpJVI/7KoZ+u0Rh/1BqLHTVwCQlqLJodyT19ZOfFz0AUHEXxuuZfkaqKBCGfSOb17ECaOsBf+IUmNY/G9RfWKgc0uYE7ACX08z3B6Y9Fo/09hO2EVhJHHEgs=
  file:
    - 'flesch.js'
    - 'flesch.min.js'
  on:
    tags: true
